# Generated by Django 4.1.3 on 2022-12-20 19:29

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField(default=10000)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('RUB', 'RUB')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Out_of_stock', 'Out_of_stock')], default='Available', max_length=255)),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=1, validators=[core.validators.check_raiting])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raiting', to='car_dealership.car')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Car_dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('characteristic', models.TextField(blank=True)),
                ('contact', models.EmailField(max_length=254)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.car')),
            ],
            options={
                'verbose_name': 'Автосалон',
                'verbose_name_plural': 'Автосалоны',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_dealership.category'),
        ),
    ]
